name: 'deploy-helm-releases'
description: ''
inputs:
  releases:
    description: ''
    required: true
  kubeconfig:
    description: ''
    required: false
  kubeconfig_file:
    description: ''
    required: false
    default: ${{ github.workspace }}/kubeconfig
  max_history:
    description: ''
    default: '3'
runs:
  using: 'composite'
  steps:
    - run: echo '${{ inputs.kubeconfig }}' > ${{ inputs.kubeconfig_file }} && chmod 0400 ${{ inputs.kubeconfig_file }}
      if: inputs.kubeconfig
      shell: bash
    - run: |
        for RELEASE in ${{ inputs.releases }}; do
          source "${RELEASE}/parameters"
          helm upgrade --install ${RELEASE_NAME} ${CHART} \
              --namespace ${NAMESPACE} \
              --values "${RELEASE}/values" \
              --version ${CHART_VERSION} \
              --repo ${REPOSITORY} \
              --history-max ${{ inputs.max_history }} \
              --debug ${EXTRA_ARGS}
        done
      shell: bash
      env:
        KUBECONFIG: ${{ inputs.kubeconfig_file }}