name: deploy-helm-releases
description: ''
inputs:
  releases:
    description: ''
    required: true
  max_history:
    description: ''
    default: '3'
runs:
  using: composite
  steps:
    - run: |
        for RELEASE in ${{ inputs.releases }}; do
          source "${RELEASE}/parameters"
          helm upgrade --install ${RELEASE_NAME} ${CHART} \
              --namespace ${NAMESPACE} \
              --values "${RELEASE}/values" \
              --version ${CHART_VERSION} \
              --repo ${REPOSITORY} \
              --history-max ${{ inputs.max_history }} \
              --debug ${EXTRA_ARGS}
        done
      shell: bash